import React from 'react'

function Footer() {
  return (
    <div className='footer'>
        <sre style={{display:"flex",}}><h3>SUPPORT AND SERVICES</h3> <h4 style={{marginLeft:"30px",marginTop:"10px"}}>   <i class="bi bi-twitter"></i>  <i class="bi bi-facebook"> </i> <i class="bi bi-instagram"> </i></h4></sre>
     <div className='footer-1'>
     <h6>Watches in Mumbai:<span style={{color:"grey",}}> Bandra, Oberoi Mall, R City Mall, Lower Parel, Fort Mumbai, Ghatkopar, Kurla(W), Shivaji Airport, Khar LinkingRoad, Vashi Sector 17, Kalyan-Murbad Rd, L.T Road, Mumbai</span>
     Watches in Dehradun:<span  style={{color:"grey"}}>Rajpur Road </span> Watches in Lucknow:<span  style={{color:"grey"}}>Hazratganj, Phoenix Mall, fun mall, Phoenix United, Ansal API </span> Watches in Sri Ganganagar:<span style={{color:"grey"}}> Sri Ganganagar </span> Watches in Hyderabad: <span style={{color:"grey"}}>Jubilee Hills, Capital Mall, Somajiguda, Himayat Nagar, Trade Centre, Kamala Nagar, MADHAPUR, Banjara Hills .</span>
     Watches in Noida:<span style={{color:"grey"}}> Sector 18, GIP Mall, Mall of India .</span>. Watches in Indore:<span style={{color:"grey"}}>Rasoma Square </span> Watches in Chennai:<span style={{color:"grey"}}> Pondy Bazaar, OMR, Anna Nagar, Velachery, Vr Mall, Cathedral Road, Express Avenue, Gandhi Nagar, Phoenix Mkt City .</span> Watches in Jaipur:<spn style={{color:"grey"}}>Divya Mall, Malviya Nagar, M I Road, Hanuman Nagar .</spn>  Watches in Ahmedabad: <span style={{color:"grey"}}> Alphaone, Maninagar, CG Road, 4D Square Mall, TRP Mall, Palladium Mall .</span> Watches in Raipur:
     <span style={{color:"grey"}}>Jaistambh Chowk, Ambuja Mall . </span> Watches in Bengaluru: <span style={{color:"grey"}}>Forum Mall, Phoenix Mall, E City, Kammanahalli, Marathahalli, Sarjapura, Koramangala, Indiranagar, Bel Road, MG Road, Jayanagar, Banashankari, Hsr Layout, Commercial St., Global Mall, Malleshwaram, Bannerghatta Rd, K R Puram .</span> Watches in Gurugram:<span style={{color:"grey"}}>Sapphire Mall, Ambience Mall, Mgf Gurgaon . Watches in Pune: Paud Road, Phoenix Mall, Westend Mall, Satara Road .</span> Watches in Varanasi:<span style={{color:"grey"}}> Kuber Complex, Durgakund, Maqbool AlamRoad . </span>Watches in Gwalior: <span style={{color:"grey"}}> Db City Mall</span> Watches in Chandigarh:
     <span style={{color:"grey"}}> Sector-17E, Elante Mall . </span> Watches in Ludhiana:<span style={{color:"grey"}}> Sarabha Nagar, Ghumar Mandi .</span>Watches in New Delhi: <span style={{color:"grey"}}> Connaught Place, Rajouri Garden, Vegas Mall, Lajpat Nagar, Pacific Mall, Delhi Terminal 3, Ambience Mall, Karolbagh, South Extension, Pitampura . </span> Watches in Amritsar:  <span style={{color:"grey"}}> Amritsar, MALL OF AMRITSAR .</span> Watches in Kochi:<span style={{color:"grey"}}> Lulu Mall, Shunmugham Road .</span>Watches in Trivandrum:   <span style={{color:"grey"}}>Kowdiar, Lulu Mall .</span>Watches in Thane: <span style={{color:"grey"}}>Thane (W), Viviana Mall, Gladys Alwares road .</span> Watches in Kolkata:<span style={{color:"grey"}}> Park Street, Rajarhat, Mani Square, City Centre, Acropolis Mall, Lindsey Street, Behala .</span> Watches in Patna:<span style={{color:"grey"}}>Frazer Road, Chajjubagh, Boring Rd, JAGDEO PATH, KANKARBAGH .</span> Watches in Gautam Budh Nagar:<span style={{color:"grey"}}> Gaur City Mall .</span> Watches in Bhopal:<span style={{color:"grey"}}> Db Mall, Malviya Nagar .</span> Watches in Bhubaneswar: 
     <span style={{color:"grey"}}> Master Canteen, Chandrasekarpur, Rasulgarh . </span> Watches in Kozhikode: <span style={{color:"grey"}}>Calicut .</span>Watches in Surat:  <span style={{color:"grey"}}> Athwa Lines, VR Mall, Ghod dod Rd .</span>Watches in Jalandhar: <span style={{color:"grey"}}> Jalandhar .</span> Watches in Coimbatore: <span style={{color:"grey"}}>Brookefield, Avinashi Road, R.S. Puram .</span>Watches in Siliguri: <span style={{color:"grey"}}>City Centre Mall . </span> Watches in Ranchi:  <span style={{color:"grey"}}> Nucleus Mall, M G Main Road . </span>Watches in Guwahati: <span style={{color:"grey"}}>City Centre, Roodraksh Mall .</span>Watches in Salem: <span style={{color:"grey"}}> Fairlands, Omalur Road . </span> Watches in Panaji:  <span style={{color:"grey"}}> Ozari . </span> Watches in Navi Mumbai:  <span style={{color:"grey"}}> Seawoods, Belapur . </span> 
     Watches in Visakhapatnam:<span style={{color:"grey"}}> Vip Road, Dwarakanagar .</span>Watches in Nashik: <span style={{color:"grey"}}>Samarth Nagar</span> Watches in Vijayawada: <span style={{color:"grey"}}>M.G. Road .</span>Watches in Madurai: <span style={{color:"grey"}}> Anna Nagar, Northveli Street .</span> Watches in Jodhpur: <span style={{color:"grey"}}>Sardarpura . </span> Watches in Udaipur: <span style={{color:"grey"}}> CelebrationMall, Ashok Nagar .</span>Watches in Prayagraj:<span style={{color:"grey"}}> Civil Lines . </span> Watches in Durgapur: <span style={{color:"grey"}}>Junction Mall .</span> Watches in Jamshedpur: <span style={{color:"grey"}}> P&M City Centre .</span> Watches in Kanpur:  <span style={{color:"grey"}}>Ppn Market .</span> Watches in Mangalore: <span style={{color:"grey"}}> Deepa Plaza .</span>Watches in Rajkot: <span style={{color:"grey"}}>Azzaro Square . </span> Watches in Mysore: <span style={{color:"grey"}}> Devaraj Urs Road .</span> Watches in Ghaziabad:  <span style={{color:"grey"}}> Mahagun Mall, Shipra Mall, Ambedkar Road . </span> Watches in Pondicherry <span style={{color:"grey"}}> Mission Street . </span>  
     Watches in Agra: <span style={{color:"grey"}}> Sanjay Place . </span> Watches in Nagercoil:  <span style={{color:"grey"}}> KP Road . </span> Watches in Vadodara:  <span style={{color:"grey"}}>RaceCourse Circle . </span> Watches in Belgaum: <span style={{color:"grey"}}> Tilakwadi .</span> Watches in Bathinda:  <span style={{color:"grey"}}>Mall Road .</span>Watches in Secunderabad: <span style={{color:"grey"}}>M.G.Road .</span>Watches in Aurangabad: <span style={{color:"grey"}}> Khatod Complex . </span> Watches in Rohtak:  <span style={{color:"grey"}}>Model Town .</span> Watches in Kolhapur:  <span style={{color:"grey"}}>The ICON Upper .</span> Watches in Dimapur:  <span style={{color:"grey"}}> Nyamo Lotha Road .</span>Watches in Thrissur: <span style={{color:"grey"}}> Ikkanda Warrier Rd .</span>. Watches in Hubli: <span style={{color:"grey"}}>Coen Road . </span> Watches in Nagpur: <span style={{color:"grey"}}> Sadar, Medical Square .</span>Watches in Karnal: <span style={{color:"grey"}}> Kunjpura Road . </span> Watches in Erode: <span style={{color:"grey"}}>Cutchery Street .</span> Watches in Aligarh: <span style={{color:"grey"}}>Centre Point .</span>Watches in Tiruchirapalli: <span style={{color:"grey"}}> Cantonment, Tiruchirapalli . </span> 
     Watches in Nanded: <span style={{color:"grey"}}> Iti Corner . </span> Watches in Dibrugarh:  <span style={{color:"grey"}}> H.S. Road .</span>Watches in Tirupur:  <span style={{color:"grey"}}> Valarmathi .</span> Watches in Udupi: <span style={{color:"grey"}}>THENKPETE .</span>Watches Watches in Tiruchirapalli: <span style={{color:"grey"}}>Cantonment, Tiruchirapalli .</span> Watches in Nanded:  <span style={{color:"grey"}}> Iti Corner .</span>  Watches in Dibrugarh:<span style={{color:"grey"}}> H.S. Road .</span>Watches in Tirupur:  <span style={{color:"grey"}}>Valarmathi .</span>. Watches in Udupi:  <span style={{color:"grey"}}> THENKPETE .</span> Watches in Baramati: <span style={{color:"grey"}}>Karbhari Chowk .</span>. Watches in Patiala:<span style={{color:"grey"}}> Bhupindra Road . </span>Watches in Gorakhpur: <span style={{color:"grey"}}> Bank Road . </span> Watches in Mohali:  <span style={{color:"grey"}}>3B2 Mohali .</span> Watches in Pernem:<span style={{color:"grey"}}> Mopa Airport .</span> Watches in Srinagar:<span style={{color:"grey"}}>Srinagar .</span></h6>
     </div>
     <h4>© 2022 Helios - The Watch Store. All Rights Reserved. Titan Company Limited.</h4>
    </div>
  )
}

export default Footer